#!/bin/bash
# Update and install system dependencies
apt-get update
apt-get install -y libproj-dev proj-data proj-bin
apt-get install -y libgeos-dev
apt-get install -y gdal-bin
apt-get install -y libgdal-dev

# Use conda to install cartopy and its dependencies
conda install -c conda-forge cartopy matplotlib==3.6.0 netcdf4 h5netcdf
